from __future__ import annotations

import os
import shutil
import sys
import tempfile
import textwrap
from pathlib import Path, PurePosixPath
from uuid import uuid4


REPO_ROOT = Path(__file__).resolve().parents[1]
PACKAGE_DIR = REPO_ROOT / "causalis"
OUTPUT_DIR = REPO_ROOT / "notebooks" / "api"
HTML_OUTPUT_DIR = OUTPUT_DIR / "html"


def _relative_posix_path(path: Path, start: Path) -> str:
    return PurePosixPath(
        os.path.relpath(os.path.realpath(path), os.path.realpath(start))
    ).as_posix()


def _require_docs_dependencies():
    try:
        from sphinx.cmd.build import build_main
    except ImportError as exc:  # pragma: no cover - exercised via subprocess
        raise SystemExit(
            "Missing documentation dependencies. Install them with "
            "`pip install -e .[docs]` or `pip install sphinx myst-parser sphinx-autodoc2`."
        ) from exc

    return build_main


def _write_conf_py(source_dir: Path) -> None:
    package_path = _relative_posix_path(PACKAGE_DIR, source_dir)
    conf_text = textwrap.dedent(
        f"""
        extensions = [
            "myst_parser",
            "autodoc2",
            "sphinx.ext.napoleon",
        ]

        project = "Causalis API Reference"
        root_doc = "reference"
        source_suffix = {{
            ".md": "markdown",
        }}
        exclude_patterns = ["_build"]
        html_copy_source = True

        autodoc2_packages = [
            {{
                "path": {package_path!r},
                "module": "causalis",
            }},
        ]
        autodoc2_output_dir = "apidocs"
        autodoc2_render_plugin = "myst"
        autodoc2_module_all_regexes = [r"causalis(\\\\..*)?"]
        autodoc2_docstring_parser_regexes = [(r"causalis(\\\\..*)?", "rst")]
        autodoc2_hidden_objects = ["private", "inherited"]

        napoleon_numpy_docstring = True
        napoleon_google_docstring = False
        """
    ).strip()
    (source_dir / "conf.py").write_text(conf_text + "\n", encoding="utf-8")


def _write_reference_page(source_dir: Path) -> None:
    reference_text = textwrap.dedent(
        """
        # API Reference

        This page is auto-generated by `scripts/generate_api_reference.py`.

        ```{toctree}
        :maxdepth: 2
        :titlesonly:

        apidocs/index
        ```
        """
    ).lstrip()
    (source_dir / "reference.md").write_text(reference_text, encoding="utf-8")

    apidocs_dir = source_dir / "apidocs"
    apidocs_dir.mkdir()
    apidocs_index_text = textwrap.dedent(
        """
        # API Modules

        ```{toctree}
        :maxdepth: 3
        :titlesonly:

        causalis/causalis
        ```
        """
    ).lstrip()
    (apidocs_dir / "index.md").write_text(apidocs_index_text, encoding="utf-8")


def _build_staged_output() -> Path:
    build_main = _require_docs_dependencies()

    with tempfile.TemporaryDirectory(prefix="generate_api_reference_") as tmp_dir:
        temp_root = Path(tmp_dir)
        source_dir = temp_root / "source"
        build_dir = temp_root / "build"
        source_dir.mkdir()
        build_dir.mkdir()

        _write_conf_py(source_dir)
        _write_reference_page(source_dir)

        result = build_main(["-b", "html", str(source_dir), str(build_dir)])
        if result != 0:
            raise RuntimeError(f"Sphinx build failed with exit code {result}.")

        generated_apidocs = source_dir / "apidocs"
        if not generated_apidocs.is_dir():
            raise FileNotFoundError(f"Expected generated docs at {generated_apidocs}.")

        staged_output = OUTPUT_DIR.parent / f".{OUTPUT_DIR.name}.staged-{uuid4().hex}"
        if staged_output.exists():
            shutil.rmtree(staged_output)
        staged_output.mkdir(parents=True)

        shutil.copytree(build_dir, staged_output / "html")

    return staged_output


def _swap_output_dir(staged_output: Path) -> None:
    backup_dir = OUTPUT_DIR.parent / f".{OUTPUT_DIR.name}.backup-{uuid4().hex}"
    had_previous_output = OUTPUT_DIR.exists()

    if had_previous_output:
        os.replace(OUTPUT_DIR, backup_dir)

    try:
        os.replace(staged_output, OUTPUT_DIR)
    except Exception:
        if had_previous_output and backup_dir.exists() and not OUTPUT_DIR.exists():
            os.replace(backup_dir, OUTPUT_DIR)
        raise
    else:
        if backup_dir.exists():
            shutil.rmtree(backup_dir)


def generate_api_reference() -> Path:
    if not PACKAGE_DIR.is_dir():
        raise FileNotFoundError(f"Package directory not found: {PACKAGE_DIR}")

    OUTPUT_DIR.parent.mkdir(parents=True, exist_ok=True)
    staged_output = _build_staged_output()
    _swap_output_dir(staged_output)
    return HTML_OUTPUT_DIR


def main() -> int:
    html_dir = generate_api_reference()
    print(f"Generated HTML API reference in {html_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
